CREATE TABLE `user_quests` (
    `user_id` varchar(32) NOT NULL,
    `one_progress` int(11) NOT NULL DEFAULT 0,
    `one_claimed` tinyint(1) NOT NULL DEFAULT 0,
    `two_progress` int(11) NOT NULL DEFAULT 0,
    `two_claimed` tinyint(1) NOT NULL DEFAULT 0,
    `three_progress` int(11) NOT NULL DEFAULT 0,
    `three_claimed` tinyint(1) NOT NULL DEFAULT 0,
    `four_progress` int(11) NOT NULL DEFAULT 0,
    `four_claimed` tinyint(1) NOT NULL DEFAULT 0,
    `five_progress` int(11) NOT NULL DEFAULT 0,
    `five_claimed` tinyint(1) NOT NULL DEFAULT 0,
    `six_progress` int(11) NOT NULL DEFAULT 0,
    `six_claimed` tinyint(1) NOT NULL DEFAULT 0,
    `seven_progress` int(11) NOT NULL DEFAULT 0,
    `seven_claimed` tinyint(1) NOT NULL DEFAULT 0,
    `num_completed` int(11) NOT NULL DEFAULT 0,
    `num_full_completed` int(11) NOT NULL DEFAULT 0,
    `full_claimed` tinyint(1) NOT NULL DEFAULT 0,
    `fastest_full_millis` mediumtext NOT NULL DEFAULT 604800001,
    `easy_completed` int(11) NOT NULL DEFAULT 0,
    `medium_completed` int(11) NOT NULL DEFAULT 0,
    `hard_completed` int(11) NOT NULL DEFAULT 0,
    `very_hard_completed` int(11) NOT NULL DEFAULT 0,
    `auto_claim` tinyint(1) NOT NULL DEFAULT 1,
    KEY `USER_ID` (`user_id`),
    CONSTRAINT `USER_ID` FOREIGN KEY (`user_id`) REFERENCES `users` (`user_id`) ON DELETE CASCADE
);