package dev.boarbot.entities.boaruser;

import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.List;

public record StatsData(
    long bucks,
    long highestBucks,
    int dailies,
    int dailiesMissed,
    Timestamp lastDailyTimestamp,
    String lastBoar,
    String favBoar,
    long totalBoars,
    long highestBoars,
    int uniques,
    int highestUniques,
    int boarStreak,
    int highestStreak,
    boolean notificationsOn,
    int blessings,
    int highestBlessings,
    int streakBless,
    int highestStreakBless,
    int questBless,
    int highestQuestBless,
    int uniqueBless,
    int highestUniqueBless,
    int otherBless,
    int highestOtherBless,
    int powerupAttempts,
    int powerupWins,
    int perfectPowerups,
    int fastestPowerup,
    double avgPowerupPlacement,
    List<String> bestPrompts,
    int miraclesAmt,
    int highestMiraclesAmt,
    int miraclesActive,
    int miraclesUsed,
    int miracleRolls,
    int miraclesMostUsed,
    int miracleBestBucks,
    String miracleBestRarity
) {
    public StatsData() {
        this(
            0,
            0,
            0,
            0,
            null,
            null,
            null,
            0,
            0,
            0,
            0,
            0,
            0,
            false,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            new ArrayList<>(),
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            null
        );
    }
}
